format = """
$container\
$all
"""

right_format = "$time"

[character]
disabled = false
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 1000
format = '[ 󱎫 $duration ](white dimmed)'

[container]
disabled = false
symbol = "󰡨 "
style = "bold green dimmed"
format = "[$symbol$name ]($style)"

[directory]
disabled = false
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold black"

[git_status]
format     = '[$all_status$ahead_behind](white dimmed) '
ahead      = '[\(${count}⇡\)](green dimmed)'
behind     = '[\(${count}⇣\)](red dimmed)'
diverged   = '[\(${ahead_count}⇡${behind_count}⇣\)](purple dimmed)'
conflicted = '[  ](bold orange dimmed)'
stashed    = '[  ${count} ](white dimmed)'
staged     = '[ ${count} ](cyan dimmed)'
untracked  = '[󰻭 ${count} ](green dimmed)'
modified   = '[ ${count} ](yellow dimmed)'
deleted    = '[󱀷 ${count} ](red dimmed)'

[memory_usage]
threshold = 70
format = "[ Mem(${ram_pct})](bold red) "
disabled = false

[package]
disabled = true

[time]
disabled = false
format = '[ $time ](white dimmed)'
time_format = '%Y-%m-%d %R'

[username]
disabled = true
style_user = "bold blue dimmed"
show_always = true
